import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { AuthProvider } from '@/authentication/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Wish it',
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <div className='flex-1'>{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
