import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { AuthProvider } from '@/authentication/AuthContext';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from '@/config/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Wish it',
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider theme={theme}>
            <Navbar />
            <div className='flex-1'>{children}</div>
            <Footer />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
